version: "3.0"

services:
  web:
    image: nginx
    ports:
     - "80:80"
    volumes:
     - ../cmd/client/grpc-react-app/dist:/usr/share/nginx/html
      
  proxy:
    image: nginx
    ports:
     - "8199:8199"
    volumes:
     - ./conf.d/grpc_proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
     - server
     
  server:
    build: 
      dockerfile: Dockerfile.grpc_server
    ports:
      - 8090:8090
    command: /app/grpc_server
    restart: always
    depends_on:
     db:
        condition: service_started

  db:
    build:
      dockerfile: Dockerfile.db
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=example
    command: --default-authentication-plugin=mysql_native_password --init-file=/app/create-example-db.sql
  

  test:
   image: ubuntu
   depends_on:
     db:
       condition: service_started
   command: sh -c "while true; do sleep 5; date; done"